import type { Metadata } from "next"

// Application Component || Define Imports
// =======================================================================================
// =======================================================================================
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// Application Component || Define Exports
// =======================================================================================
// =======================================================================================
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
